#include "ConeEmitter.h"




void ConeEmitter::emit(ParticleSystem *ps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000ACE begin
{
}
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000ACE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
