#include "GravityModifier.h"

void GravityModifier::modify(ParticleSystem *ps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000AD1 begin
{
    for(u32 i = 0; i < ps->particles.size(); i++)
    {
        f32 dist = glm::distance(position, ps->particles[i].position);
        vec3 gravity = force * (position - ps->particles[i].position) / (dist*dist);
        ps->particles[i].acceleration += gravity;
    }
}
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000AD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
