#include "ParticleSystem.h"
#include "PointEmitter.h"
#include "ConeEmitter.h"
#include "GravityModifier.h"
#include "WindModifier.h"

ParticleSystem::~ParticleSystem()
{
    emitters.clear();
    modifiers.clear();
}

void ParticleSystem::update(f32 deltaTime)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000884 begin
{
    for(u32 i=0; i<particles.size(); i++)
    {
        particles[i].life -= deltaTime;
        if(particles[i].life < 0.0f)
        {
            particles.erase(particles.begin()+i);
        }
    }
    for(u32 i=0; i<emitters.size(); i++)
    {
        emitters[i]->emit(this);
    }

    for(u32 i=0; i<modifiers.size(); i++)
    {
        modifiers[i]->modify(this);
    }

    for(u32 i=0; i<particles.size(); i++)
    {
        particles[i].velocity = particles[i].acceleration * deltaTime;
        particles[i].position = particles[i].velocity * deltaTime;
    }
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000884 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000886 begin
{
    glMatrixMode(GL_MODELVIEW_MATRIX);

    glPushMatrix();
        glLoadIdentity();
        glColor3f(1.0,1.0,1.0);
        glBegin( GL_POINTS);
            for(u32 i=0; i<particles.size(); i++)
            {
                glVertex3fv(glm::value_ptr(particles[i].position));
            }
        glEnd();
    glPopMatrix();
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000886 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createPointEmitter(u8 spawnRate, vec2 lifeInterval, vec3 position, vec2 speedInterval)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009AE begin
{
    ParticleEmitter *pe = new PointEmitter(spawnRate, lifeInterval, position, speedInterval);
    emitters.push_back(pe);
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009AE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createConeEmitter(u8 spawnRate, vec2 lifeInterval, vec3 position, vec2 speedInterval, vec2 spreadInterval)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009B8 begin
{
    ParticleEmitter *pe = new ConeEmitter(spawnRate, lifeInterval, position, speedInterval, spreadInterval);
    emitters.push_back(pe);
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009B8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createGravityModifier(vec3 position, f32 force)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009C2 begin
{
    ParticleModifier *pm = new GravityModifier(position, force);
    modifiers.push_back(pm);
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009C2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createWindModifier(vec3 position, vec3 direction, f32 force)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009D8 begin
{
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009D8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createParticle(vec3 position, vec3 velocity, f32 life)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088D begin
{
    particles.push_back(Particle(position, velocity, life));
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
