#include "ParticleModifier.h"




void ParticleModifier::modify(ParticleSystem *ps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088B begin
{
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
