#include "ParticleSystem.h"




void ParticleSystem::update()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000884 begin
{
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000884 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000886 begin
{
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:0000000000000886 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createPointEmitter(vec3 position, u8 spawnRate, vec2 speedIntervall)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009AE begin
{
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009AE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createConeEmitter(vec3 position, u8 spawnRate, vec2 speedIntervall, f32 angle, f32 spreadAngle)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009B8 begin
{
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009B8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createGravityModifier(vec3 position, f32 force)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009C2 begin
{
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009C2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createWindModifier(vec3 position, vec3 direction, f32 force)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009D8 begin
{
}
// section -64--88-0-4-56cbe92f:13a604c9fa2:-8000:00000000000009D8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void ParticleSystem::createParticle(vec3 position, vec3 velocity)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088D begin
{
}
// section -64--88-0-10--b955d3a:13a5bfc4741:-8000:000000000000088D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
