#include "PointEmitter.h"




void PointEmitter::emit(ParticleSystem *ps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000ACB begin
{
    for(u8 i=0; i<spawnRate; i++)
    {
        ps->createParticle(position,vec3(1,1,1),1.0);
    }
}
// section -64--88-0-4-425b3777:13a63811884:-8000:0000000000000ACB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
